CREATE DATABASE `smarttrack` /*!40100 DEFAULT CHARACTER SET utf8 */;
CREATE TABLE `carriersservices` (
  `CPaCarier` varchar(4) CHARACTER SET utf8mb4 NOT NULL,
  `CPaSize` smallint(6) DEFAULT NULL,
  `CPaServiceStart` smallint(6) DEFAULT NULL,
  `CPaServiceLenght` smallint(6) DEFAULT NULL,
  `CpaMaskStart` int(11) DEFAULT NULL,
  `CpaMaskLenght` int(11) DEFAULT NULL,
  `CpaMaskValue` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `CpaServiceValue` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `CpaSystemServices` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `CPaName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `CpaServiceDesciption` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `CpaLogoPath` varchar(150) CHARACTER SET utf8mb4 DEFAULT NULL,
  `CpaSenderAccountStart` int(11) DEFAULT NULL,
  `CpaSenderAccountLenght` int(11) DEFAULT NULL,
  `CpaDateTimeModified` datetime DEFAULT NULL,
  KEY `CPaCarier` (`CPaCarier`),
  KEY `CPaSize` (`CPaSize`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `employees` (
  `EmpID` int(11) NOT NULL AUTO_INCREMENT,
  `EmpFirstName` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpMiddleName` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpLastName` varchar(200) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpLocationID` varchar(32) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpPhone` varchar(18) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpExtension` varchar(15) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpEmail` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpTitle` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpDateTimeModified` datetime DEFAULT CURRENT_TIMESTAMP,
  `EmpMemo` longtext,
  `EmpCompanyID` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpWebPassword` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpCreateAlertsForAll` tinyint(1) DEFAULT NULL,
  `EmpWebAllowSearch` tinyint(1) DEFAULT NULL,
  `EmpWebAllowAlerts` tinyint(1) DEFAULT NULL,
  `EmpWebAllowPickUps` tinyint(1) DEFAULT NULL,
  `EmpCreatedDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `EmpEditedDate` datetime(6) DEFAULT NULL,
  `EmpForwardLabel` tinyint(1) DEFAULT NULL,
  `EmpForwardCompany` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpForwardAddress1` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpForwardAddress2` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpForwardAddress3` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpCCEmail` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpMisc1` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `EmpMisc2` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `StaGroupName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (`EmpID`),
  KEY `EmpCompanyID` (`EmpCompanyID`),
  KEY `EmpID` (`EmpID`)
) ENGINE=InnoDB AUTO_INCREMENT=508 DEFAULT CHARSET=utf8;
CREATE TABLE `itemlog` (
  `IloAutoID` int(11) NOT NULL AUTO_INCREMENT,
  `IloStaCode` int(11) DEFAULT NULL,
  `IloStaGroup` int(11) DEFAULT NULL,
  `IloID` varchar(12) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloTrackingNo` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCarrier` varchar(10) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloSender` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloEmployeeFirstName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloEmployeeLasttName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloLocName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloLocID` varchar(32) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloService` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloServiceDescripton` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloDateTime` datetime(6) DEFAULT NULL,
  `IloUseName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloStatusID` varchar(5) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloNotes` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloPadLocation` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloSigID` int(11) DEFAULT NULL,
  `IloReportNo` int(11) DEFAULT NULL,
  `IloCustom1` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom2` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom3` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom4` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom5` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom6` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom7` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom8` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom9` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCustom10` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloAlert` tinyint(1) DEFAULT NULL,
  `IloMasterLabelID` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IloCommitNum` int(11) DEFAULT NULL,
  `IloDelManNum` varchar(50) CHARACTER SET utf8mb4 DEFAULT 'NA',
  `IloDeleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`IloAutoID`),
  KEY `IloAutoID` (`IloAutoID`),
  KEY `IloCarrier` (`IloCarrier`),
  KEY `IloCustom1` (`IloCustom1`),
  KEY `IloCustom10` (`IloCustom10`),
  KEY `IloCustom2` (`IloCustom2`),
  KEY `IloCustom3` (`IloCustom3`),
  KEY `IloCustom4` (`IloCustom4`),
  KEY `IloCustom5` (`IloCustom5`),
  KEY `IloCustom6` (`IloCustom6`),
  KEY `IloCustom7` (`IloCustom7`),
  KEY `IloCustom8` (`IloCustom8`),
  KEY `IloCustom9` (`IloCustom9`),
  KEY `IloEmployeeFirstName` (`IloEmployeeFirstName`),
  KEY `IloEmployeeLasttName` (`IloEmployeeLasttName`),
  KEY `IloID` (`IloID`),
  KEY `IloLocID` (`IloLocID`),
  KEY `IloLocName` (`IloLocName`),
  KEY `IloSender` (`IloSender`),
  KEY `IloService` (`IloService`),
  KEY `IloStaCode` (`IloStaCode`),
  KEY `IloStatusID` (`IloStatusID`),
  KEY `IloTrackingNo` (`IloTrackingNo`),
  KEY `IloUseName` (`IloUseName`)
) ENGINE=InnoDB AUTO_INCREMENT=86283 DEFAULT CHARSET=utf8;
CREATE TABLE `itemstatus` (
  `IeSAutoID` int(11) NOT NULL AUTO_INCREMENT,
  `IeSStaCode` int(11) DEFAULT NULL,
  `IeSStaGroup` int(11) DEFAULT NULL,
  `IeSID` varchar(12) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSTrackingNo` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCarrier` varchar(10) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSSender` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSEmployeeFirstName` varchar(70) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSEmployeeLastName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSLocName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSLocID` varchar(32) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSService` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSServiceDescripton` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSDateTime` datetime(6) DEFAULT NULL,
  `IeSUseName` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSStatusID` varchar(5) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSReportNo` int(11) DEFAULT NULL,
  `IeSCustom1` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom2` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom3` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom4` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom5` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom6` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom7` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom8` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom9` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCustom10` varchar(80) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeAlert` tinyint(1) DEFAULT NULL,
  `IeSMasterLabelID` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `IeSCommitNum` int(11) DEFAULT NULL,
  `IeSDeleteMe` tinyint(1) DEFAULT NULL,
  `IeSDelManNum` varchar(50) CHARACTER SET utf8mb4 DEFAULT 'NA',
  `IesEmpID` int(11) DEFAULT NULL,
  PRIMARY KEY (`IeSAutoID`),
  KEY `IeSAutoID` (`IeSAutoID`),
  KEY `IeSCarrier` (`IeSCarrier`),
  KEY `IeSCustom1` (`IeSCustom1`),
  KEY `IeSCustom10` (`IeSCustom10`),
  KEY `IeSCustom2` (`IeSCustom2`),
  KEY `IeSCustom3` (`IeSCustom3`),
  KEY `IeSCustom4` (`IeSCustom4`),
  KEY `IeSCustom5` (`IeSCustom5`),
  KEY `IeSCustom6` (`IeSCustom6`),
  KEY `IeSCustom7` (`IeSCustom7`),
  KEY `IeSCustom8` (`IeSCustom8`),
  KEY `IeSCustom9` (`IeSCustom9`),
  KEY `IeSEmployeeLastName` (`IeSEmployeeLastName`),
  KEY `IeSEmployeeName` (`IeSEmployeeFirstName`),
  KEY `IeSID` (`IeSID`),
  KEY `IeSLocID` (`IeSLocID`),
  KEY `IeSSender` (`IeSSender`),
  KEY `IeSStaCode` (`IeSStaCode`),
  KEY `IeSStatusID` (`IeSStatusID`),
  KEY `IeSUseName` (`IeSUseName`)
) ENGINE=InnoDB AUTO_INCREMENT=477066 DEFAULT CHARSET=utf8;
CREATE TABLE `senders` (
  `SenID` int(11) NOT NULL AUTO_INCREMENT,
  `SenName` varchar(30) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenAddress1` varchar(30) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenAddress2` varchar(30) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenCity` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenState` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenZip` varchar(9) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenCountry` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenPhone` varchar(18) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenEmail` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenAccount` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenDateTimeModified` datetime DEFAULT CURRENT_TIMESTAMP,
  `SenAccount2` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenMisc1` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SenMisc2` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (`SenID`),
  KEY `sndcode` (`SenID`)
) ENGINE=InnoDB AUTO_INCREMENT=4700 DEFAULT CHARSET=utf8;
CREATE TABLE `signatures` (
  `SigID` int(11) NOT NULL AUTO_INCREMENT,
  `SigSignature` longblob,
  `sFilename` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `SigCommitNum` int(11) DEFAULT NULL,
  PRIMARY KEY (`SigID`),
  KEY `SigIloAutoID` (`SigID`)
) ENGINE=InnoDB AUTO_INCREMENT=42604 DEFAULT CHARSET=utf8;
